const dataProduct = [
  {
    id: 5,
    alias: "sipolos-kaos-polos-cotton-combed-lengan-pendek-regular-fit-basic-caramel",
    name: "Kaos Polos Cotton Combed Lengan Pendek Regular Fit Basic - Caramel, S",
    image: "https://x-api.alpha-x.id/files/product/5.jpg",
    price: 200000,
    discount: 20,
    location: "Kota Bandung",
    review: 4.1,
    total_review: 20,
    publish_date: "2022-03-05 14:22:22",
  },
  {
    id: 6,
    alias: "fortklass-kaos-striple-salur-pria-katun-belang-garis-unisex-orange-m",
    name: "FortKlass Kaos Striple Salur Pria Katun Belang Garis Unisex - Orange, M",
    image: "https://x-api.alpha-x.id/files/product/6.jpg",
    price: 75000,
    discount: 0,
    location: "Jakarta Barat",
    review: 2.1,
    total_review: 278,
    publish_date: "2022-03-05 14:22:22",
  },
  {
    id: 7,
    alias: "kaos-polos-cotton-combed-24s-lengan-pendek-premium-putih-s",
    name: "Kaos Polos Cotton Combed 24s Lengan Pendek Premium - Putih, S",
    image: "https://x-api.alpha-x.id/files/product/7.jpg",
    price: 500000,
    discount: 0,
    location: "Jakarta Timur",
    review: 4.8,
    total_review: 489,
    publish_date: "2022-03-05 14:22:22",
  },
  {
    id: 1,
    alias: "kaos-jumbo-pria-big-size-xxxxl",
    name: "Kaos Jumbo Pria Big Size XXXXL",
    image: "https://x-api.alpha-x.id/files/product/1.jpg",
    price: 75000,
    discount: 15,
    location: "Bandung",
    review: 4.9,
    total_review: 120,
    publish_date: "2022-03-05 14:11:47",
  },
  {
    id: 1,
    alias: "kaos-jumbo-pria-big-size-xxxxl",
    name: "Kaos Jumbo Pria Big Size XXXXL",
    image: "https://x-api.alpha-x.id/files/product/1.jpg",
    price: 75000,
    discount: 15,
    location: "Bandung",
    review: 4.9,
    total_review: 120,
    publish_date: "2022-03-05 14:11:47",
  },
  {
    id: 1,
    alias: "kaos-jumbo-pria-big-size-xxxxl",
    name: "Kaos Jumbo Pria Big Size XXXXL",
    image: "https://x-api.alpha-x.id/files/product/1.jpg",
    price: 75000,
    discount: 15,
    location: "Bandung",
    review: 4.9,
    total_review: 120,
    publish_date: "2022-03-05 14:11:47",
  },
  {
    id: 1,
    alias: "kaos-jumbo-pria-big-size-xxxxl",
    name: "Kaos Jumbo Pria Big Size XXXXL",
    image: "https://x-api.alpha-x.id/files/product/1.jpg",
    price: 75000,
    discount: 15,
    location: "Bandung",
    review: 4.9,
    total_review: 120,
    publish_date: "2022-03-05 14:11:47",
  },
  {
    id: 1,
    alias: "kaos-jumbo-pria-big-size-xxxxl",
    name: "Kaos Jumbo Pria Big Size XXXXL",
    image: "https://x-api.alpha-x.id/files/product/1.jpg",
    price: 75000,
    discount: 15,
    location: "Bandung",
    review: 4.9,
    total_review: 120,
    publish_date: "2022-03-05 14:11:47",
  },
];

export default dataProduct;
